CREATE TABLE "Shelters" (
  "ShelterID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PopulationCapacity" integer,
  "SupplyVolume" integer,
  "Latitude" float,
  "Longitude" float,
  "EstablishedDate" date,
  "DecommisionDate" date DEFAULT null
);

CREATE TABLE "Survivors" (
  "SurvivorID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" varchar(128),
  "LastName" varchar(128),
  "BirthDate" date
);

CREATE TABLE "ShelterSurvivors" (
  "ShelterSurvivors" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SurvivorId" integer,
  "ShelterID" integer
);

CREATE TABLE "BeanRequests" (
  "BeanRequestID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SurvivorID" integer,
  "Approved" bool,
  "RequestTime" date
);

CREATE TABLE "BeanRequestItem" (
  "BeanRequestItemID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "CannedBeanID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "NumberOfCans" integer,
  "BeanRequestID" integer,
  PRIMARY KEY ("BeanRequestItemID", "CannedBeanID")
);

CREATE TABLE "BeanMissions" (
  "BeanMissionID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ShelterID" integer,
  "PlannedStart" date,
  "PlannedEnd" date,
  "ActualEnd" date
);

CREATE TABLE "MissionYieldItems" (
  "MissionYieldItemID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CannedBeanID" integer,
  "NumberOfCans" integer,
  "BeanMissionID" integer
);

CREATE TABLE "CannedBeans" (
  "CannedBeanID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BeanType" varchar(128),
  "Grams" float
);

CREATE TABLE "BeanSupplies" (
  "BeanSupplyID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ShelterID" integer,
  "CannedBeanID" integer,
  "ConsumedDate" date DEFAULT null
);

CREATE TABLE "Managers" (
  "ManagerID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SurvivorID" integer
);

ALTER TABLE "ShelterSurvivors" ADD FOREIGN KEY ("SurvivorId") REFERENCES "Survivors" ("SurvivorID");

ALTER TABLE "ShelterSurvivors" ADD FOREIGN KEY ("ShelterID") REFERENCES "Shelters" ("ShelterID");

ALTER TABLE "BeanRequests" ADD FOREIGN KEY ("SurvivorID") REFERENCES "Survivors" ("SurvivorID");

ALTER TABLE "BeanRequestItem" ADD FOREIGN KEY ("BeanRequestID") REFERENCES "BeanRequests" ("BeanRequestID");

ALTER TABLE "BeanMissions" ADD FOREIGN KEY ("ShelterID") REFERENCES "Shelters" ("ShelterID");

ALTER TABLE "MissionYieldItems" ADD FOREIGN KEY ("CannedBeanID") REFERENCES "CannedBeans" ("CannedBeanID");

ALTER TABLE "MissionYieldItems" ADD FOREIGN KEY ("BeanMissionID") REFERENCES "BeanMissions" ("BeanMissionID");

ALTER TABLE "BeanSupplies" ADD FOREIGN KEY ("ShelterID") REFERENCES "Shelters" ("ShelterID");

ALTER TABLE "BeanSupplies" ADD FOREIGN KEY ("CannedBeanID") REFERENCES "CannedBeans" ("CannedBeanID");

ALTER TABLE "Managers" ADD FOREIGN KEY ("SurvivorID") REFERENCES "Survivors" ("SurvivorID");
