DROP TABLE "BeanRequestItem"; 

CREATE TABLE "BeanRequestItem" (
  "BeanRequestItemID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CannedBeanID" integer,
  "NumberOfCans" integer,
  "BeanRequestID" integer
);


ALTER TABLE "BeanRequestItem" ADD FOREIGN KEY ("CannedBeanID") REFERENCES "CannedBeans" ("CannedBeanID");

ALTER TABLE "BeanRequestItem" ADD FOREIGN KEY ("BeanRequestID") REFERENCES "BeanRequests" ("BeanRequestID");

ALTER TABLE "ShelterSurvivors" DROP CONSTRAINT "ShelterSurvivors_SurvivorId_fkey";

ALTER TABLE "ShelterSurvivors" RENAME COLUMN "SurvivorId" TO "SurvivorID";

ALTER TABLE "ShelterSurvivors" ADD FOREIGN KEY ("SurvivorID") REFERENCES "Survivors" ("SurvivorID");