name: "DB Deployment"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tf_deploy:
    name: "DB deploy"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: Create Database if not exists
        run: |
          echo "Checking if FalloutDB exists..."
          DB_EXISTS=$(PGPASSWORD=${{ secrets.DB_PASS }} psql -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='${{ secrets.DB_NAME }}'")
          if [[ "$DB_EXISTS" != "1" ]]; then
            echo "Creating ${{ secrets.DB_NAME }}..."
            PGPASSWORD=${{ secrets.DB_PASS }} psql -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d postgres -c "CREATE DATABASE ${{ secrets.DB_NAME }}"
            echo "${{ secrets.DB_NAME }} created."
          else
            echo "${{ secrets.DB_NAME }} already exists."
          fi