name: Migrations

on:
  workflow_run:
    workflows: ["DB Deployment"]
    types:
      - completed
    branches:
      - dev
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Run Flyway Migrations
        run: |
          echo "Running migrations on DB: ${{ secrets.DB_NAME }}:${{ secrets.DB_PORT }} using branch ${{ github.event.workflow_run.head_branch }}"
          docker run --rm \
            -v ${{ github.workspace }}/migrations:/flyway/migrations \
            flyway/flyway:latest \
            -url=jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASS }} \
            -locations=filesystem:/flyway/migrations \
            -placeholders.DB_NAME=${{ secrets.DB_NAME }} \
            -placeholders.MANAGER_APP_PASS=${{ secrets.MANAGER_APP_PASS }} \
            -placeholders.SURVIVOR_APP_PASS=${{ secrets.SURVIVOR_APP_PASS }} \
            -placeholders.REPORTING_APP_PASS=${{ secrets.REPORTING_APP_PASS }} \
            -placeholders.ADMIN_PASS=${{ secrets.ADMIN_PASS }} \
            migrate