name: "Terraform Deployment"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - name: "Initialize Terraform"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan

      - name: "Terraform Apply"
        run: terraform apply -auto-approve

      - name: "Save DB Endpoint"
        run: echo "DB_HOST=$(terraform output -raw db_endpoint)" >> $GITHUB_ENV
      